### ISSUE TITLE
Folder with many assets seems to cause editor hang

### ISSUE THREAD

**Issue by patrick-han** [FlaxEngine/FlaxEngine#2057]
**Issue description:**

Editor hangs after some time after I open a folder with many assets in it. At first I thought it was related to selecting many items and trying to delete them at once (I discovered this when trying to delete the bistro scene assets from my project), but it seems it just happens even when doing nothing and waiting for the thumbnails to load. The last few log files included in the zipped project are relevant, as I tried multiple times and used task manager each time to end the process.

Interestingly, after I deleted a Sponza asset I had imported (which was in a separate set of folders), this bug seems to happen instantaneously when trying to open the BistroInterior_Wine folder, with none of the thumbnails having a chance to load.

**Steps to reproduce:**

1. In the content browser open the folder Content/Models/BistroInterior/BistroInterior_Wine
2. Wait some time

**Minimal reproduction project:**

Here: https://drive.proton.me/urls/SZCXQNXRT4#UywwmRJ7KpGj

**Flax version:**

1.7.1

**Comment by mafiesto4** [comment]
I was able to reproduce it and it looks like it was caused by asset tooltip trying to wait for asset loading task to finish from main thread but the loading task was waiting on main thread to sync texture data. Fixed in ff195eeccba237f98b66a504359877f53eb3b2f8.

**Comment by patrick-han** [comment]
Thanks! But it seems only the initial problem of opening the folder + hanging is resolved. I still get a freeze when trying to delete a bunch of the assets. For example, these first 36:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/47380073/9c3ed0cb-e7ef-4bb3-8c54-b8d433f40aef)

Hitting delete with these selected immediately locks everything up.

I switched to the master branch build to test this.

**Comment by mafiesto4** [comment]
Fixed deadlocks/errors in 60202a3addf0179d2162ea6e86176f5ee0a3dcbf + d7b17ae0a6804f6d82a91b1bdfaba6be57078585.

Fixed importing `dds` files a5e072da3191740c9c7ad5ac5fc2ad3057c53be5.
