### ISSUE TITLE
[Proposal] Only allow panning view in node editors with either MMB or RMB

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#2466]
_Edit: MMB was removed in the latest master but the issue with the right click menu opening does still exist._

**Issue description:**

Currently you can pan the view in any node editor with MMB _and_ RMB. Why are there two ways to pan the editor?
I think we should remove one (more on which one in a bit) for making it more consistent because having two options that do the exactly same thing is weird.

### Which way to pan should we remove?
I think having RMB as the button for panning is better than MMB due to the simple fact that Unreal uses it. So people who have spent a lot of time in Unreal Engines node editors don't have to re- train their muscle memory. Also RMB has a way bigger area to click on, so it's more ergonomic (not to mention that the feel of the MMB click sucks on some mice).

However, when you currently start panning with RMB while hovering the mouse over a node, once you let go of RMB the right click context menu pops up. This really feels unpolished and also requires an unnecessary click for the user to get rid of it.

*Conclusion*
So either we fix the right click menu problem and make RMB the one and only option to pan _or_ we go with MMB and all of it's downsides (but at least no right click menu).

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/b6efde8c-85a9-4824-a4a1-f52ef9198ac8

_Panning with RMB_

https://github.com/FlaxEngine/FlaxEngine/assets/111653551/4ea5ed90-b320-4f7e-b3ac-33d9807bece6

_Panning with MMB_

**Steps to reproduce:**

1. Create an asset that has a node editor (Material, Animation Graph, Visual Script, etc.)
2. Try panning with MMB or RMB
3. When panning with RMB, try hovering over a node to see the right click menu pop up

**Minimal reproduction project:**

none

**Flax version:**

1.8

**Comment by Muzz** [comment]
this is already fixed in master. It's only RMB and middle mouse was removed because you'd accidently delete connections when panning.

**Comment by xxSeys1** [comment]
Just tested on the latest master build in the launcher and MMB is indeed removed but the issue with the right click menu opening does still happen.

**Comment by mafiesto4** [comment]
Fixed context menu in f19977a9561caf5a199379ed183aa6321e240cbb
