### ISSUE TITLE
Bugs with the Camera View Orientation in the Editor

### ISSUE THREAD

**Issue by Evildea** [FlaxEngine/FlaxEngine#276]
**Issue description:**
There are two bugs:
1. The orientations don't line up with the view. Basically, if I go into a front orientation it places the scene far off to the right.
2. The orientations should automatically swap to Orthographic. People don't use orientations in perspective.

![image](https://user-images.githubusercontent.com/35228400/108945534-e0a28100-76b0-11eb-82df-1642c521be72.png)

**Steps to reproduce:**
Simply change the Orientation of the camera

You can see a video of me doing this here:
https://user-images.githubusercontent.com/35228400/108945646-17789700-76b1-11eb-8b1c-cc184516e89e.mp4

**Minimal reproduction project:**
The current Master Branch version in Github.

**Comment by jb-perrier** [comment]
Will check that tonight.

**Comment by jb-perrier** [comment]
I made some test, and i'm unable to reproduce this bug, the camera just don't move. Is there more details about it ? 
I've spotted that Right/Left/Bottom/Top are inverted depending on how you understand these words.

**Comment by Evildea** [comment]
@jb-perrier Hey, so I made another video of the issue. Here you can see it occurring in the Prefab Editor.
https://drive.google.com/file/d/1ZoaYKNGtyMNUCifzW4BkX_p-KDxWc5Vc/view?usp=sharing

It's not correctly showing the front nor changing to orthographic view.
If you're still not seeing an issue then perhaps the error is related to my high DPI monitor? I know Flax has DPI issues.

**Comment by jb-perrier** [comment]
Oh ok, i get it. The camera is facing front at the cam position, not at the target one or at world origin. We could definitly improve that to be more user friendly.

It doesn't switch to ortho to let the choice to the user, in some situation use cam orientation + persp was useful for me.
A setting to for that is the way to go i think.

**Comment by mafiesto4** [comment]
I think was was fixed/improved in https://github.com/FlaxEngine/FlaxEngine/pull/284. Can you confirm it works as it should now?

**Comment by Evildea** [comment]
I just tested it and it still doesn't work. Here is the video. I remember working with @jb-perrier on this and it was working in the end so I'm not sure what has happened since. Perhaps his latest changes haven't been integrated yet?
https://user-images.githubusercontent.com/35228400/112095907-73233b00-8bf1-11eb-9ef6-394913df9bae.mp4

**Comment by mafiesto4** [comment]
It was implemented for main editor viewport only. I added impl for prefab window too: c0d0083cc2a18a81ddd23c986a5db016c9e6944f.
