### ISSUE TITLE
[BUG] Undo on `Spline Keyframes` undos to wrong value

### ISSUE THREAD

**Issue by xxSeys1** [FlaxEngine/FlaxEngine#3256]
**Issue description:**

When I drag on a Spline Keyframe parameter and then undo my change using CTRL + Z, the parameter is undone to the wrong value:

https://github.com/user-attachments/assets/3900bc02-a53e-44b6-b156-529a2a4cf300

When I manually enter a value, the undo does not work at all. The point where the Properties panel contents disappear is where I pressed CTRL + Z so many times that it removes the spline actor from the scene:

https://github.com/user-attachments/assets/ae97613d-b3b6-44e8-9340-2516e278a1b9

**Steps to reproduce:**

1. Add a new Spline actor into your scene
2. Edit any value of a Spline Keyframe (either by dragging the value box or by typing in a value)
3. Undo

**Minimal reproduction project:**

none

**Flax version:**

latest launcher master as of 3/3/2025, 1.9.6606

**Comment by mafiesto4** [comment]
Fixed in b36be959472214b076b2fccb94846f982d332cf3.

**Comment by xxSeys1** [comment]
@mafiesto4 I can still reproduce this in latest master:

https://github.com/user-attachments/assets/3b43ab59-1a99-472d-aa83-2c75dfef42ba
