### ISSUE TITLE
Window and Help menu items are unclickable.

### ISSUE THREAD

**Issue by jayrulez** [FlaxEngine/FlaxEngine#4]
**Issue description:**

Window and help menus in the tool menu become unclickable.

**Steps to reproduce:**

Just open the editor and try to click help or window.

This seems to be intermittent.

**Comment by mafiesto4** [comment]
Do you use interface scale or a high-dpi screen? Maybe that's the reason of the issue.

**Comment by jayrulez** [comment]
I'm using a 4k screen. I also tried upping the ui scale to 2 but it doesn't seem to apply as the value still shows as 1 when I restart the editor.

**Comment by jayrulez** [comment]
The hitbox for the elements seem to be smaller than what is displayed as if I hover slightly then at a certain position they become clickable.

**Comment by vulcan-dev** [comment]
I've also just experienced the same thing, the close button doesn't work but if I double click it minimises and maximises.

**Comment by kira0x1** [comment]
I had the same issue. I found a fix by going into optons -> interface -> Use Native Windows System and setting it true. ( check the box )

Hope this helps.

**Comment by jb-perrier** [comment]
This should be fixed with #8 .

**Comment by duanyunlun** [comment]
same issue. With kira0x1's fix method to make it work, but still have this issue in borderless mode, though I set the DPI to 100%

**Comment by jb-perrier** [comment]
Have you builded the editor from source, or the last release ?
