### ISSUE TITLE
Menu misaligned in Linux Editor

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#636]
**Issue description:**
The editor places the menu items left of the menu bar entries which might even be left of the leftmost position on the screen.

**Steps to reproduce:**
Open the Linux editor on e.g. Ubuntu 21.04 and click on File in the menu bar.

**Flax version:**
1.2.6224

https://user-images.githubusercontent.com/34131388/135729136-b0540c59-c725-4c82-88f8-b2c4cd79f616.mp4

**Comment by nothingTVatYT** [comment]
It seems to happen only if you use UI scaling other than 1.

**Comment by GoaLitiuM** [comment]
Most likely fixed by #915

**Comment by nothingTVatYT** [comment]
This is still a problem in Version 1.6.6345 and only happens when there is more than one screen. The further right in the monitors arrangement the bigger the offset is from the menu title to the dropdown menu.

**Comment by nothingTVatYT** [comment]
PR #1610 fixes that.
