### ISSUE TITLE
Cannot dock panel once it was undocked in Linux

### ISSUE THREAD

**Issue by nothingTVatYT** [FlaxEngine/FlaxEngine#667]
**Issue description:**
The game panel cannot be docked again once you undock it. The docking positions show up on mouse over but it won't dock.

**Steps to reproduce:**
Undock the game window. Grab the panel and try to dock it again.

**Flax version:**
Current master branch Nov 11th 2021

**Comment by Crawcik** [comment]
I tried it and it's fixed now

**Comment by Flavelius** [comment]
It's still happening on ubuntu 22.04 in my case, i posted a screenshot in the bug channel on discord.
